### ISSUE TITLE
Missing data from the dataset

### ISSUE THREAD

**Issue by JiachengDeng** [dongliangcao/Self-Supervised-Multimodal-Shape-Matching#2]
I downloaded the four datasets FAUST, SCAPE, SHREC19 and SURREAL-5K through the download links provided by the authors. But when I run the training program, it indicates that the FAUST, SCAPE and SHREC19 datasets are missing *.mat data under dist_path, while SURREAL-5K is missing *.vts and *.mat. So I would like to ask if the data needs additional post-processing? Also, where to download the SHREC'16 dataset and how to do the data processing?
I look forward to hearing from you！

**Comment by dongliangcao** [comment]
Hi Jiacheng,

Thanks for your interest about the project. 

Indeed, there are pre-processing required for data evaluation, the *.mat data under dist_path contains the geodesic distance matrix for quantitative evaluation. You can use [preprocess.py](https://github.com/dongliangcao/Self-Supervised-Multimodal-Shape-Matching/blob/main/preprocess.py) to obtain the geodesic distance matrix:
`python preprocess.py --data_root ../data/FAUST_r --no_eig --no_normalize`

The SURREAL-5K is a synthetic dataset derived by [SMPL](https://smpl.is.tue.mpg.de/), so they are already in one-to-one correspondences (e.g. 1st vertex in shape X corresponds to 1st vertex in shape Y). You can easily generate *.vts, which contains the ground-truth correspondences, by using `np.arange(1,len(vertices)+1)`, but since our method is an unsupervised method and we don't evaluate on the SURREAL-5K dataset, so you can simply set `return_corr: false` in the [train.yaml](https://github.com/dongliangcao/Self-Supervised-Multimodal-Shape-Matching/blob/main/options/train.yaml#L21). 

As for the download of SHREC'16 dataset, we provide you the [link](https://github.com/pvnieo/cp2p-pfarm-benchmark/tree/master) for downloading both the training and test dataset.
