### ISSUE TITLE
About why not training on surreal 230k dataset

### ISSUE THREAD

**Issue by 2019EPWL** [dongliangcao/Self-Supervised-Multimodal-Shape-Matching#4]
Thanks for your excellent work.  I found the all datasets used in this work almost only contain 50-200 shapes. The DPC and Corrnet3D both trained on the surreal 230k dataset, but this work doesn't show the compared result on the surreal 230k datasets.

**Comment by dongliangcao** [comment]
Hello, the reason is that we want to demonstrate that the better *generalization ability* of our method compared to DPC and Corrnet3D. We include the result of our method trained on the surreal 230k dataset in Tab. 10 in the supplementary material, which you can find in the [arxiv version](https://arxiv.org/pdf/2303.10971.pdf).

**Comment by 2019EPWL** [comment]
I see, Tab. 10 shows the cross-datasets result on 5k and 230k SURREAL datasets. However, it doesn't show the baselines' results such as Corrnet3D and DPC.

**Comment by dongliangcao** [comment]
The baselines' results such as Corrnet3D and DPC trained on 230k SURREAL dataset are shown in Tab. 3 in the main paper. Since even trained with 230k dataset their performance are much worse than ours, so we didn't train them on 5k SURREAL dataset. If you are curious about their performance regarding the amount of training data, you can compare Tab. 2 and Tab. 3 for Corrnet3D and DPC.

**Comment by 2019EPWL** [comment]
Okk, thank you very much. Another little question is about what's the point num used in each shape for training.

**Comment by dongliangcao** [comment]
We use the original resolution of the SURREAL dataset for training, if I remember correctly the number of vertices is 6890, since it is based on the SMPL.
